package com.myspace.poc_bancolombia;

/**
 * This class was automatically generated by the data modeler tool.
 */
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class PQR implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String numeroRadicado;
	private java.lang.String descripcionPQR;
	private java.lang.String estadoPQR;
	private java.lang.String fechaCreacion;
	private java.lang.String entidad;
	private java.lang.String productoCanal;
	private java.lang.String tipologia;
	private java.lang.String usuarioReporta;
	private java.lang.String cantidadTransacciones;
	private java.lang.String valorSolicitado;
	private java.lang.String valorNoEntregado;
	private java.lang.String canal;
	private java.lang.String numeroProducto;
	private java.lang.String usuarioRealizaTransaccion;
	private java.lang.String diasEstimadosSolucion;
	private java.lang.String fechaEstimadaSolucion;
	private java.lang.String responsable;

	public PQR() {
	}
    
    @JsonProperty("numeroRadicado")
	public java.lang.String getNumeroRadicado() {
		return this.numeroRadicado;
	}

    @JsonProperty("numeroRadicado")
	public void setNumeroRadicado(java.lang.String numeroRadicado) {
		this.numeroRadicado = numeroRadicado;
	}

    @JsonProperty("descripcionPQR")
	public java.lang.String getDescripcionPQR() {
		return this.descripcionPQR;
	}
    
    @JsonProperty("descripcionPQR")
	public void setDescripcionPQR(java.lang.String descripcionPQR) {
		this.descripcionPQR = descripcionPQR;
	}

    @JsonProperty("estadoPQR")
	public java.lang.String getEstadoPQR() {
		return this.estadoPQR;
	}

    @JsonProperty("estadoPQR")
	public void setEstadoPQR(java.lang.String estadoPQR) {
		this.estadoPQR = estadoPQR;
	}

    @JsonProperty("fechaCreacion")
	public java.lang.String getFechaCreacion() {
		return this.fechaCreacion;
	}

    @JsonProperty("fechaCreacion")
	public void setFechaCreacion(java.lang.String fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}
    
    @JsonProperty("entidad")
	public java.lang.String getEntidad() {
		return this.entidad;
	}

    @JsonProperty("entidad")
	public void setEntidad(java.lang.String entidad) {
		this.entidad = entidad;
	}

    @JsonProperty("productoCanal")
	public java.lang.String getProductoCanal() {
		return this.productoCanal;
	}

    @JsonProperty("productoCanal")
	public void setProductoCanal(java.lang.String productoCanal) {
		this.productoCanal = productoCanal;
	}

    @JsonProperty("tipologia")
	public java.lang.String getTipologia() {
		return this.tipologia;
	}

    @JsonProperty("tipologia")
	public void setTipologia(java.lang.String tipologia) {
		this.tipologia = tipologia;
	}

    @JsonProperty("usuarioReporta")
	public java.lang.String getUsuarioReporta() {
		return this.usuarioReporta;
	}
	
	@JsonProperty("usuarioReporta")
	public void setUsuarioReporta(java.lang.String usuarioReporta) {
		this.usuarioReporta = usuarioReporta;
	}

    @JsonProperty("cantidadTransacciones")
	public java.lang.String getCantidadTransacciones() {
		return this.cantidadTransacciones;
	}

    @JsonProperty("cantidadTransacciones")
	public void setCantidadTransacciones(java.lang.String cantidadTransacciones) {
		this.cantidadTransacciones = cantidadTransacciones;
	}

    @JsonProperty("valorSolicitado")
	public java.lang.String getValorSolicitado() {
		return this.valorSolicitado;
	}

    @JsonProperty("valorSolicitado")
	public void setValorSolicitado(java.lang.String valorSolicitado) {
		this.valorSolicitado = valorSolicitado;
	}

    @JsonProperty("valorNoEntregado")
	public java.lang.String getValorNoEntregado() {
		return this.valorNoEntregado;
	}

    @JsonProperty("valorNoEntregado")
	public void setValorNoEntregado(java.lang.String valorNoEntregado) {
		this.valorNoEntregado = valorNoEntregado;
	}

    @JsonProperty("canal")
	public java.lang.String getCanal() {
		return this.canal;
	}

	@JsonProperty("canal")
	public void setCanal(java.lang.String canal) {
		this.canal = canal;
	}

    @JsonProperty("numeroProducto")
	public java.lang.String getNumeroProducto() {
		return this.numeroProducto;
	}

    @JsonProperty("numeroProducto")
	public void setNumeroProducto(java.lang.String numeroProducto) {
		this.numeroProducto = numeroProducto;
	}

    @JsonProperty("usuarioRealizaTransaccion")
	public java.lang.String getUsuarioRealizaTransaccion() {
		return this.usuarioRealizaTransaccion;
	}

    @JsonProperty("usuarioRealizaTransaccion")
	public void setUsuarioRealizaTransaccion(
			java.lang.String usuarioRealizaTransaccion) {
		this.usuarioRealizaTransaccion = usuarioRealizaTransaccion;
	}

    @JsonProperty("diasEstimadosSolucion")
	public java.lang.String getDiasEstimadosSolucion() {
		return this.diasEstimadosSolucion;
	}

    @JsonProperty("diasEstimadosSolucion")
	public void setDiasEstimadosSolucion(java.lang.String diasEstimadosSolucion) {
		this.diasEstimadosSolucion = diasEstimadosSolucion;
	}

    @JsonProperty("fechaEstimadaSolucion")
	public java.lang.String getFechaEstimadaSolucion() {
		return this.fechaEstimadaSolucion;
	}

    @JsonProperty("fechaEstimadaSolucion")
	public void setFechaEstimadaSolucion(java.lang.String fechaEstimadaSolucion) {
		this.fechaEstimadaSolucion = fechaEstimadaSolucion;
	}

    @JsonProperty("responsable")
	public java.lang.String getResponsable() {
		return this.responsable;
	}

    @JsonProperty("responsable")
	public void setResponsable(java.lang.String responsable) {
		this.responsable = responsable;
	}

	public PQR(java.lang.String numeroRadicado,
			java.lang.String descripcionPQR, java.lang.String estadoPQR,
			java.lang.String fechaCreacion, java.lang.String entidad,
			java.lang.String productoCanal, java.lang.String tipologia,
			java.lang.String usuarioReporta,
			java.lang.String cantidadTransacciones,
			java.lang.String valorSolicitado,
			java.lang.String valorNoEntregado, java.lang.String canal,
			java.lang.String numeroProducto,
			java.lang.String usuarioRealizaTransaccion,
			java.lang.String diasEstimadosSolucion,
			java.lang.String fechaEstimadaSolucion, java.lang.String responsable) {
		this.numeroRadicado = numeroRadicado;
		this.descripcionPQR = descripcionPQR;
		this.estadoPQR = estadoPQR;
		this.fechaCreacion = fechaCreacion;
		this.entidad = entidad;
		this.productoCanal = productoCanal;
		this.tipologia = tipologia;
		this.usuarioReporta = usuarioReporta;
		this.cantidadTransacciones = cantidadTransacciones;
		this.valorSolicitado = valorSolicitado;
		this.valorNoEntregado = valorNoEntregado;
		this.canal = canal;
		this.numeroProducto = numeroProducto;
		this.usuarioRealizaTransaccion = usuarioRealizaTransaccion;
		this.diasEstimadosSolucion = diasEstimadosSolucion;
		this.fechaEstimadaSolucion = fechaEstimadaSolucion;
		this.responsable = responsable;
	}

}