package com.myspace.poc_bancolombia;

import java.time.LocalDate;
import java.time.Period;

import com.fasterxml.jackson.annotation.JsonProperty;
/**
 * This class was automatically generated by the data modeler tool.
 */
public class PQRs implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.poc_bancolombia.PQR> PQR;

	public PQRs() {
		java.util.List<com.myspace.poc_bancolombia.PQR> PQR = new java.util.ArrayList<com.myspace.poc_bancolombia.PQR>();
		this.PQR = PQR;
	}

    @JsonProperty("PQR")
	public java.util.List<com.myspace.poc_bancolombia.PQR> getPQR() {
		return this.PQR;
	}
    @JsonProperty("PQR")
	public void setPQR(java.util.List<com.myspace.poc_bancolombia.PQR> PQR) {
		this.PQR = PQR;
	}

	public boolean validarFechaCreacion(int fecha){
		boolean result = false;
		for (com.myspace.poc_bancolombia.PQR item : this.PQR) {
			//System.out.println("Fecha Creacion: " + item.getFechaCreacion());
			String[] fechaPQR = item.getFechaCreacion().split("-");
			int anioPQR = Integer.parseInt(fechaPQR[0]);
			if (anioPQR < fecha){
				System.out.println("Fecha Creacion menor que fecha: " + item.getFechaCreacion());
				result = true;
			}
		}
		return result;
	}

	public boolean validarPQRAbiertos(String tipologia, String estado){
		boolean result = false;
		for (com.myspace.poc_bancolombia.PQR item : this.PQR) {
			//System.out.println("Validando PQR tipologia: "+ item.getTipologia() +", estado: " + item.getEstadoPQR() + " fechaCreacion: " + item.getFechaCreacion());
			if(item.getTipologia().toUpperCase().equals(tipologia.toUpperCase()) && item.getEstadoPQR().toUpperCase().equals(estado.toUpperCase())){
				//System.out.println("Entro a IF tipologia: "+ item.getTipologia() +", estado: " + item.getEstadoPQR() + " fechaCreacion: " + item.getFechaCreacion());
				LocalDate now = LocalDate.now();
				LocalDate fecha = LocalDate.parse(item.getFechaCreacion());
				Period period = Period.between(now, fecha);
				int diff = Math.abs(period.getDays());
				//System.out.println("Diferencia en dias: " + diff);
				if(diff >= 15){
					System.out.println("Se encontro PQR con 15 o mas dias abierto: " + item.getNumeroRadicado());
					result = true;
				}
			}
		}
		return result;
	}

	public PQRs(java.util.List<com.myspace.poc_bancolombia.PQR> PQR) {
		this.PQR = PQR;
	}

}