package com.myspace.poc_bancolombia;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ReglasDO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.myspace.poc_bancolombia.PQRWrapper pqrWrapper;
	private java.lang.Integer responseCode;

	private com.myspace.poc_bancolombia.ProcessRequest processRequest;

	private com.myspace.poc_bancolombia.PQRRequest pqrRequest;

	public ReglasDO() {
	}

	public com.myspace.poc_bancolombia.PQRWrapper getPqrWrapper() {
		return this.pqrWrapper;
	}

	public void setPqrWrapper(com.myspace.poc_bancolombia.PQRWrapper pqrWrapper) {
		this.pqrWrapper = pqrWrapper;
	}

	public java.lang.Integer getResponseCode() {
		return this.responseCode;
	}

	public void setResponseCode(java.lang.Integer responseCode) {
		this.responseCode = responseCode;
	}

	public com.myspace.poc_bancolombia.ProcessRequest getProcessRequest() {
		return this.processRequest;
	}

	public void setProcessRequest(
			com.myspace.poc_bancolombia.ProcessRequest processRequest) {
		this.processRequest = processRequest;
	}

	public com.myspace.poc_bancolombia.PQRRequest getPqrRequest() {
		return this.pqrRequest;
	}

	public void setPqrRequest(com.myspace.poc_bancolombia.PQRRequest pqrRequest) {
		this.pqrRequest = pqrRequest;
	}

	public ReglasDO(com.myspace.poc_bancolombia.PQRWrapper pqrWrapper,
			java.lang.Integer responseCode,
			com.myspace.poc_bancolombia.ProcessRequest processRequest,
			com.myspace.poc_bancolombia.PQRRequest pqrRequest) {
		this.pqrWrapper = pqrWrapper;
		this.responseCode = responseCode;
		this.processRequest = processRequest;
		this.pqrRequest = pqrRequest;
	}

}